import type { ErpData } from "./types";

const today = new Date().toISOString().slice(0, 10);

export const defaultErpData: ErpData = {
  conectaCodes: [
    {
      id: "code-install",
      description: "Instalação FTTA",
      code: "CN-FTTA-001",
      points: 1,
      value: 420,
    },
    {
      id: "code-splice",
      description: "Fusão de fibra",
      code: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
    },
    {
      id: "code-maintenance",
      description: "Manutenção corretiva",
      code: "CN-MANUT-003",
      points: 0.75,
      value: 260,
    },
  ],
  production: [
    {
      id: "prod-alpha-1",
      empresa: "ALPHA TELECOM",
      date: today,
      sp: "45872",
      cabo: "CTO-12 / FO-08",
      local: "Rua das Palmeiras, 120",
      status: "OK",
      equipe: "Equipe Norte",
      materiais: ["80m fibra", "2 conectores"],
      conectaCodeId: "code-install",
      conectaCode: "CN-FTTA-001",
      points: 1,
      value: 420,
      launchedConecta: true,
      rawMessage: "Instalação concluída com sucesso.",
    },
    {
      id: "prod-beta-1",
      empresa: "BETA TELECOM",
      date: today,
      sp: "61244",
      cabo: "BFO-07",
      local: "Central Zona Sul",
      status: "Pendente",
      equipe: "Equipe Sul",
      materiais: ["30m cabo", "1 CTO"],
      conectaCodeId: "code-maintenance",
      conectaCode: "CN-MANUT-003",
      points: 0.75,
      value: 260,
      launchedConecta: false,
      rawMessage: "Atendimento aguardando liberação.",
    },
    {
      id: "prod-gamma-1",
      empresa: "GAMMA TELECOM",
      date: today,
      sp: "77410",
      cabo: "CFO-03",
      local: "Base Central",
      status: "OK",
      equipe: "Equipe Campo",
      materiais: ["60m fibra"],
      conectaCodeId: "code-splice",
      conectaCode: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
      launchedConecta: true,
      rawMessage: "Fusão executada e lançada.",
    },
  ],
  finance: [
    {
      id: "fin-alpha-initial",
      empresa: "ALPHA TELECOM",
      date: today,
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 12500,
      paid: true,
    },
    {
      id: "fin-alpha-rent",
      empresa: "ALPHA TELECOM",
      date: today,
      description: "Despesas fixas",
      type: "Saída",
      category: "Administrativo",
      amount: 3100,
      paid: false,
    },
    {
      id: "fin-beta-initial",
      empresa: "BETA TELECOM",
      date: today,
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 9400,
      paid: true,
    },
    {
      id: "fin-beta-supplies",
      empresa: "BETA TELECOM",
      date: today,
      description: "Materiais de campo",
      type: "Saída",
      category: "Operacional",
      amount: 1850,
      paid: true,
    },
    {
      id: "fin-gamma-initial",
      empresa: "GAMMA TELECOM",
      date: today,
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 18400,
      paid: true,
    },
  ],
  vr: [
    {
      id: "vr-alpha-1",
      empresa: "ALPHA TELECOM",
      funcionario: "Rafael Martins",
      equipe: "Equipe Norte",
      diasTrabalhados: 22,
      sabados: 2,
      valorDia: 32.63,
      valorSabado: 65.26,
      amount: 783.12,
    },
    {
      id: "vr-beta-1",
      empresa: "BETA TELECOM",
      funcionario: "Juliana Rocha",
      equipe: "Equipe Sul",
      diasTrabalhados: 20,
      sabados: 1,
      valorDia: 32.63,
      valorSabado: 65.26,
      amount: 718.86,
    },
    {
      id: "vr-gamma-1",
      empresa: "GAMMA TELECOM",
      funcionario: "Felipe Almeida",
      equipe: "Equipe Campo",
      diasTrabalhados: 24,
      sabados: 3,
      valorDia: 32.63,
      valorSabado: 65.26,
      amount: 913.68,
    },
  ],
  employees: [
    {
      id: "emp-alpha-1",
      empresa: "ALPHA TELECOM",
      re: "1001",
      situacao: "ATIVO",
      nome: "Rafael Martins",
      funcionario: "Rafael Martins",
      cargo: "Coordenador",
      seguimento: "Rede",
      equipe: "Equipe Norte",
      projeto: "Acesso",
      vrDia: "32,63",
      vt: "0",
      salario: "R$ 3.800,00",
      clt: "SIM",
      carro: "Não",
      placa: "",
      admissao: "15/01/2024",
      dataAdmissao: "15/01/2024",
      vencimentoContrato45: "29/02/2024",
      vencimentoContrato90: "15/04/2024",
      eSocial: "ES-1001",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.111.222-**",
      rg: "***.221.111-**",
      nomeMae: "Patrícia Martins",
      nomePai: "Carlos Martins",
      dataNascimento: "12/08/1990",
      enderecoCompleto: "São Paulo - SP",
      nrs1035: "SIM",
      vencimentoNrs: "15/04/2026",
      possuiNrs: "SIM",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "SIM",
    },
    {
      id: "emp-alpha-2",
      empresa: "ALPHA TELECOM",
      re: "1002",
      situacao: "FERIAS",
      nome: "Camila Souza",
      funcionario: "Camila Souza",
      cargo: "Técnica de Campo",
      seguimento: "FTTA",
      equipe: "Equipe Norte",
      projeto: "Backbone",
      vrDia: "32,63",
      vt: "R$ 0,00",
      salario: "R$ 2.950,00",
      clt: "SIM",
      carro: "NÃO",
      placa: "",
      admissao: "10/03/2023",
      dataAdmissao: "10/03/2023",
      vencimentoContrato45: "24/04/2023",
      vencimentoContrato90: "08/06/2023",
      eSocial: "ES-1002",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.333.444-**",
      rg: "***.222.333-**",
      nomeMae: "Luciana Souza",
      nomePai: "Renato Souza",
      dataNascimento: "03/11/1994",
      enderecoCompleto: "Campinas - SP",
      nrs1035: "SIM",
      vencimentoNrs: "10/10/2026",
      possuiNrs: "SIM",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
    {
      id: "emp-beta-1",
      empresa: "BETA TELECOM",
      re: "2001",
      situacao: "ATIVO",
      nome: "Juliana Rocha",
      funcionario: "Juliana Rocha",
      cargo: "Analista de Operações",
      seguimento: "Operação",
      equipe: "Equipe Sul",
      projeto: "Atendimento",
      vrDia: "32,63",
      vt: "R$ 0,00",
      salario: "R$ 4.100,00",
      clt: "SIM",
      carro: "SIM",
      placa: "XYZ1A23",
      admissao: "20/06/2024",
      dataAdmissao: "20/06/2024",
      vencimentoContrato45: "04/08/2024",
      vencimentoContrato90: "18/09/2024",
      eSocial: "ES-2001",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.555.666-**",
      rg: "***.444.555-**",
      nomeMae: "Márcia Rocha",
      nomePai: "Sérgio Rocha",
      dataNascimento: "21/02/1988",
      enderecoCompleto: "São Bernardo - SP",
      nrs1035: "NÃO",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "SIM",
    },
    {
      id: "emp-beta-2",
      empresa: "BETA TELECOM",
      re: "2002",
      situacao: "AFASTADO",
      nome: "Marcos Pereira",
      funcionario: "Marcos Pereira",
      cargo: "Técnico de Rede",
      seguimento: "Rede",
      equipe: "Equipe Sul",
      projeto: "Acesso",
      vrDia: "32,63",
      vt: "R$ 0,00",
      salario: "R$ 3.250,00",
      clt: "SIM",
      carro: "NÃO",
      placa: "",
      admissao: "01/09/2022",
      dataAdmissao: "01/09/2022",
      vencimentoContrato45: "15/10/2022",
      vencimentoContrato90: "29/11/2022",
      eSocial: "ES-2002",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.777.888-**",
      rg: "***.666.777-**",
      nomeMae: "Sandra Pereira",
      nomePai: "Roberto Pereira",
      dataNascimento: "09/05/1987",
      enderecoCompleto: "Santos - SP",
      nrs1035: "SIM",
      vencimentoNrs: "01/09/2026",
      possuiNrs: "SIM",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "SIM",
    },
    {
      id: "emp-gamma-1",
      empresa: "GAMMA TELECOM",
      re: "3001",
      situacao: "ATIVO",
      nome: "Felipe Almeida",
      funcionario: "Felipe Almeida",
      cargo: "Supervisor de Campo",
      seguimento: "Campo",
      equipe: "Equipe Campo",
      projeto: "Monitoramento",
      vrDia: "32,63",
      vt: "R$ 0,00",
      salario: "R$ 4.500,00",
      clt: "SIM",
      carro: "SIM",
      placa: "ABC2D34",
      admissao: "12/02/2021",
      dataAdmissao: "12/02/2021",
      vencimentoContrato45: "28/03/2021",
      vencimentoContrato90: "12/05/2021",
      eSocial: "ES-3001",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.999.000-**",
      rg: "***.888.999-**",
      nomeMae: "Cláudia Almeida",
      nomePai: "Ricardo Almeida",
      dataNascimento: "18/12/1984",
      enderecoCompleto: "Osasco - SP",
      nrs1035: "SIM",
      vencimentoNrs: "12/02/2026",
      possuiNrs: "SIM",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "SIM",
    },
    {
      id: "emp-gamma-2",
      empresa: "GAMMA TELECOM",
      re: "3002",
      situacao: "INATIVO",
      nome: "Bianca Costa",
      funcionario: "Bianca Costa",
      cargo: "Auxiliar Administrativo",
      seguimento: "Administrativo",
      equipe: "Equipe Campo",
      projeto: "Suporte",
      vrDia: "32,63",
      vt: "R$ 0,00",
      salario: "R$ 2.600,00",
      clt: "SIM",
      carro: "NÃO",
      placa: "",
      admissao: "05/08/2023",
      dataAdmissao: "05/08/2023",
      vencimentoContrato45: "19/09/2023",
      vencimentoContrato90: "03/11/2023",
      eSocial: "ES-3002",
      cracha: "SIM",
      cartaoVrVa: "SIM",
      cpf: "***.111.000-**",
      rg: "***.000.111-**",
      nomeMae: "Ana Costa",
      nomePai: "Paulo Costa",
      dataNascimento: "27/07/1993",
      enderecoCompleto: "Barueri - SP",
      nrs1035: "NÃO",
      vencimentoNrs: "",
      possuiNrs: "NÃO",
      nrsVencido: "NÃO",
      feriasVencidas: "NÃO",
      podeTirarFerias: "NÃO",
    },
  ],
};
