import type { ErpData } from "./types";

const today = new Date().toISOString().slice(0, 10);

export const defaultErpData: ErpData = {
  conectaCodes: [
    {
      id: "code-install",
      description: "Instalação FTTA",
      code: "CN-FTTA-001",
      points: 1,
      value: 420,
    },
    {
      id: "code-splice",
      description: "Fusão de fibra",
      code: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
    },
    {
      id: "code-maintenance",
      description: "Manutenção corretiva",
      code: "CN-MANUT-003",
      points: 0.75,
      value: 260,
    },
  ],
  production: [
    {
      id: "prod-alpha-1",
      empresa: "ALPHA TELECOM",
      date: today,
      sp: "45872",
      cabo: "CTO-12 / FO-08",
      local: "Rua das Palmeiras, 120",
      status: "OK",
      equipe: "Equipe Norte",
      materiais: ["80m fibra", "2 conectores"],
      conectaCodeId: "code-install",
      conectaCode: "CN-FTTA-001",
      points: 1,
      value: 420,
      launchedConecta: true,
      rawMessage: "Instalação concluída com sucesso.",
    },
    {
      id: "prod-beta-1",
      empresa: "BETA TELECOM",
      date: today,
      sp: "61244",
      cabo: "BFO-07",
      local: "Central Zona Sul",
      status: "Pendente",
      equipe: "Equipe Sul",
      materiais: ["30m cabo", "1 CTO"],
      conectaCodeId: "code-maintenance",
      conectaCode: "CN-MANUT-003",
      points: 0.75,
      value: 260,
      launchedConecta: false,
      rawMessage: "Atendimento aguardando liberação.",
    },
    {
      id: "prod-gamma-1",
      empresa: "GAMMA TELECOM",
      date: today,
      sp: "77410",
      cabo: "CFO-03",
      local: "Base Central",
      status: "OK",
      equipe: "Equipe Campo",
      materiais: ["60m fibra"],
      conectaCodeId: "code-splice",
      conectaCode: "CN-FUSAO-002",
      points: 0.5,
      value: 180,
      launchedConecta: true,
      rawMessage: "Fusão executada e lançada.",
    },
  ],
  finance: [
    {
      id: "fin-alpha-initial",
      empresa: "ALPHA TELECOM",
      date: today,
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 12500,
      paid: true,
    },
    {
      id: "fin-alpha-rent",
      empresa: "ALPHA TELECOM",
      date: today,
      description: "Despesas fixas",
      type: "Saída",
      category: "Administrativo",
      amount: 3100,
      paid: false,
    },
    {
      id: "fin-beta-initial",
      empresa: "BETA TELECOM",
      date: today,
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 9400,
      paid: true,
    },
    {
      id: "fin-beta-supplies",
      empresa: "BETA TELECOM",
      date: today,
      description: "Materiais de campo",
      type: "Saída",
      category: "Operacional",
      amount: 1850,
      paid: true,
    },
    {
      id: "fin-gamma-initial",
      empresa: "GAMMA TELECOM",
      date: today,
      description: "Saldo inicial",
      type: "Entrada",
      category: "Caixa",
      amount: 18400,
      paid: true,
    },
  ],
  vr: [],
  employees: [],
};
